spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: nis123456
    url: jdbc:mysql://192.168.2.27/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /


